sudo: false

language: php
php:
  - 5.3

env: TEST_MYSQL_DSN="mysql:host=127.0.0.1" TEST_MYSQL_USER=travis TEST_MYSQL_PASSWORD=""

install:
  - composer install

script: phpunit --bootstrap vendor/autoload.php test
